version: '3.9'

services:
        
  app:
    hostname: app
    container_name: FreshFusionServer
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      -  .:/app
 
    env_file:
      - .env
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB}
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - 27017:27017
